notifications:
  email: false
os: linux
language: python
python: 3.8
install:
# install binary packages
- travis_retry pip install --upgrade pip setuptools wheel
# install package
- travis_retry pip install -e .
# for tests:
- travis_retry pip install codecov coverage flake8
- pip freeze
script:
#- coverage run --source=dcor_shared ./setup.py test
#- coverage report -m
- flake8 dcor_shared
- flake8 tests
after_success:
#- codecov
before_deploy:
- python setup.py sdist bdist_wheel
deploy:
  provider: pypi
  user: "ci_dcor"
  password:
    secure: "Z9Venv/ZZHJHIPPteCsDQmirPIlhIfy7QJRSL2By2U/L/M5HDKzo3f3esnB67IjaCpXpVuzKWxzWtIrhGxUxsSvMHRRCabHlA70K7tzDV++BmlTQ9cMHIM3Kh/MkTpo/sKcRNOXkXnrkY1hu1Qjcs9ScR4MVLsMP9kcp4PPNpxNnCC+YBpaRERCbZeG4asMg0J12+B7IS5KfhZRZq21MBT9ZJEGHnus18G0w6vhVhVs8Vri33K03oMJ1VrIoc9pXAac1d7V0NNGRrJOkxAqy8L0wLKKiTocMQOtxzC+WWT3QXtCWc1a5/Oi4wJPznp8R+IYECGjg4yocbFZOwUvxQtqWCY5+GKPFQIgZ2ZQ24I732uCW9A9FT0G3aK9wnIVCIlJYO5sgiv8el1O1a6ONB30r57hTWHlA1LOLlqMtf+tHlImK+bDGvprCdjjOigiXDqYasz+Hfu777HK9GcBFccVaCKenfnNlKuxhPFlg/naID8gubub/bpdlJSnlNlKxnqGpsIN/oWOKyGnmyziZKXQuQESw/VkKx8vK4PS0irXPeF4smRquzy+9SRLeeNsDmpktNRljqfHV6N5Uc1jB3/H/7d4R64aCXd2h3Uq+D9G5UgC1fGfopRz0neMg9WPWVwWmoXBGB+DXjLL+0OrgUWcIHnaviLbUxQXUHniZ3o0="
  on:
    tags: true
  skip_cleanup: true
  skip_existing: true
